title: Albin Englund (aenglund)
name: Albin Englund
username: aenglund
email: mail@albinenglund.com
description: "I am an iOS-developer employeed at Tactel in Malmö, Sweden. Graduated with a Bachelor of Science in Computer Software Engineering from Linköping University in 2013."
baseurl: ""
url: "http://albinenglund.com"
paginate: 5
paginate_path: ":num"

# Social
rss: "/feed.xml"
github: "http://github.com/aenglund"
twitter: "http://twitter.com/albinenglund"
linkedin: "http://se.linkedin.com/pub/albin-englund/48/483/b40"
facebook: "http://facebook.com/albin.englund.14"

# Build settings
markdown: kramdown
