title: Albin Englund (aenglund)
name: Albin Englund
author: Albin Englund
username: aenglund
email: mail@albinenglund.com
description: "Albin Englund (aenglund) - Scrum Master, iOS-developer and Project Manager employeed at HiQ Gothenburg, Sweden. Graduated with a Bachelor of Science in Computer Software Engineering from Linköping University in 2013."
baseurl: ""
url: "http://blog.albinenglund.com"
paginate: 5
paginate_path: "/page/:num/"
permalink: "/:year/:month/:day/:title.html"

destination: public

# Google Analytics
google_analytics_tracking_id: "UA-65345262-1"

# Social
rss: "/feed.xml"
github: "http://github.com/aenglund"
twitter: "http://twitter.com/albinenglund"
linkedin: "http://se.linkedin.com/pub/albin-englund/48/483/b40"
facebook: "http://facebook.com/albin.englund.14"

# Build settings
markdown: kramdown
highlighter: rouge

# File exclusion
exclude: ['Gemfile.lock', 'Gemfile']

